### ISSUE TITLE
ecma5.json not found

### ISSUE THREAD

**Issue by patriclougheed** [mikethedj4/kodeWeave#3]
FYI this happens on your site and my test site;

XMLHttpRequest cannot load https://ternjs.net/defs/ecma5.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mikethedj4.github.io' is therefore not allowed access. The response had HTTP status code 404.

Attempts at direct access of the json fails too. Not sure if this breaks any functionality.

**Comment by mikethedj4** [comment]
I just made a new release that fixes this problem. Thanks for telling me :)
